"""Configure Unreal /project tasks for native Harbor artifact replay."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import shlex

from harbor.models.task.config import ArtifactConfig, TaskConfig


EXCLUDED = [".git", "Binaries", "Intermediate", "Saved", "DerivedDataCache", "node_modules", ".venv", "__pycache__"]
PROJECT_ARTIFACTS = [{"source": "/project", "destination": "project", "exclude": EXCLUDED}]
FULL_PROJECT_ARTIFACTS = [{"source": "/project", "destination": "project", "exclude": []}]
LEGACY_COMPOSE = '''services:
  main:
    build:
      context: ${CONTEXT_DIR}/../environment
      dockerfile: ../tests/Dockerfile
'''
COMPOSE = '''services:
  main:
    build:
      context: ${CONTEXT_DIR}/..
      dockerfile: tests/Dockerfile
'''
LEGACY_GPU_SERVICE = '''    gpus: all
    environment:
      NVIDIA_DRIVER_CAPABILITIES: graphics,utility,compute,display
'''
GPU_SERVICE = LEGACY_GPU_SERVICE + '''    volumes:
      - type: bind
        source: ${NVIDIA_VULKAN_ICD:-/usr/share/vulkan/icd.d/nvidia_icd.json}
        target: /etc/vulkan/icd.d/nvidia_icd.json
        read_only: true
        bind:
          create_host_path: false
'''
LEGACY_GPU_AGENT_COMPOSE = 'services:\n  main:\n' + LEGACY_GPU_SERVICE
LEGACY_GPU_COMPOSE = COMPOSE + LEGACY_GPU_SERVICE
GPU_AGENT_COMPOSE = 'services:\n  main:\n' + GPU_SERVICE
GPU_COMPOSE = COMPOSE + GPU_SERVICE


def verifier_compose(task: Path) -> str:
    agent = task / 'environment/docker-compose.yaml'
    return GPU_COMPOSE if agent.is_file() and agent.read_text(encoding='utf-8') == GPU_AGENT_COMPOSE else COMPOSE

BUILD_IGNORE = '''**
!environment/
!environment/**
!tests/
!tests/**
**/__pycache__/
'''
GENERATED_HEADER = "# Generated by scripts/standardize_harbor.py\n"
ORIGINAL_TEST = ".harbor-original-test.sh"
VERIFIER_ENTRYPOINT = '''#!/bin/bash
set -euo pipefail
if [ ! -d /project ] || [ -L /project ]; then
  echo "VERDICT: restored project is missing or is a symlink" >&2
  exit 2
fi
chown -hR -P -- ue4:ue4 /project
find -P /project \\( -type d -o -type f \\) -exec chmod u+rwX -- {} +
exec runuser -u ue4 -- bash /tests/.harbor-original-test.sh "$@"
'''


def ownership_entrypoint_dockerfile() -> str:
    lines = " ".join(shlex.quote(line) for line in VERIFIER_ENTRYPOINT.splitlines())
    return ("USER root\n"
            "RUN command -v runuser >/dev/null \\\n"
            f" && mv /tests/test.sh /tests/{ORIGINAL_TEST} \\\n"
            f" && printf '%s\\n' {lines} > /tests/test.sh \\\n"
            f" && chown root:root /tests /tests/test.sh /tests/{ORIGINAL_TEST} \\\n"
            f" && chmod 0555 /tests && chmod 0444 /tests/{ORIGINAL_TEST} && chmod 0755 /tests/test.sh\n"
            "USER ue4\n")


def build_input_hash(task: Path, *, partial_project: bool) -> str:
    root = task / "environment"
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root)
        if not path.is_file() or path.is_symlink() or {".git", "__pycache__"} & set(relative.parts):
            continue
        if not partial_project and relative.parts[0] == "workspace":
            continue  # Full-project verifier images never COPY the starter.
        with path.open("rb") as stream:
            checksum = hashlib.file_digest(stream, "sha256").hexdigest()
        digest.update(json.dumps([relative.as_posix(), path.stat().st_size, checksum]).encode("utf-8"))
    return digest.hexdigest()


def verifier_dockerfile(task: Path, *, partial_project: bool = False) -> str:
    dockerfile = (task / "environment/Dockerfile").read_text(encoding="utf-8")
    workspace_line = "COPY --chown=ue4:ue4 workspace/ /project/"
    if not partial_project:
        dockerfile = dockerfile.replace(workspace_line + "\n", "")
    dockerfile = dockerfile.replace("COPY --chown=ue4:ue4 workspace/", "COPY --chown=ue4:ue4 environment/workspace/")
    dockerfile = dockerfile.replace("COPY --chown=ue4:ue4 protected/", "COPY --chown=ue4:ue4 environment/protected/")
    # Harbor identifies the verifier image by tests/ alone. Include sibling
    # build inputs in that identity so concurrent versions cannot share a tag.
    digest = build_input_hash(task, partial_project=partial_project)
    return (GENERATED_HEADER + f"# Environment content SHA256: {digest}\n" + dockerfile.rstrip() +
            "\nCOPY --chown=root:root tests/ /tests/\n" + ownership_entrypoint_dockerfile())


def validate_verifier_build(task: Path) -> None:
    """Fail before launching a generated verifier with stale/missing inputs."""
    path = task / "tests/Dockerfile"
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8")
    if not text.startswith(GENERATED_HEADER):
        return
    partial = "COPY --chown=ue4:ue4 environment/workspace/ /project/" in text
    config = TaskConfig.model_validate_toml((task / "task.toml").read_text(encoding="utf-8"))
    if config.verifier.user != "root":
        raise ValueError("Generated verifier requires user=root for its ownership entrypoint")
    if text != verifier_dockerfile(task, partial_project=partial):
        raise ValueError("Verifier build inputs changed; prepare/configure this task again before replay")
    if (task / "tests/docker-compose.yaml").read_text(encoding="utf-8") != verifier_compose(task):
        raise ValueError("Generated verifier Compose definition is inconsistent")
    if (task / "tests/Dockerfile.dockerignore").read_text(encoding="utf-8") != BUILD_IGNORE:
        raise ValueError("Generated verifier build-context exclusions are inconsistent")


def artifact_toml(artifacts: list) -> str:
    entries = []
    for artifact in artifacts:
        if isinstance(artifact, str):
            entries.append(json.dumps(artifact))
        else:
            entries.append("{ " + ", ".join(f"{key} = {json.dumps(value)}" for key, value in artifact.items() if value is not None) + " }")
    return "artifacts = [" + ", ".join(entries) + "]"


def configure_task(task: Path, artifacts: list | None = None, *, partial_project: bool = False) -> None:
    artifacts = PROJECT_ARTIFACTS if artifacts is None else artifacts
    for entry in artifacts:
        artifact = ArtifactConfig(source=entry) if isinstance(entry, str) else ArtifactConfig(**entry)
        if not (artifact.source == "/project" or artifact.source.startswith("/project/")) or artifact.service not in {None, "main"}:
            raise ValueError("Unreal replay inputs must come from /project in the main service")
    path = task / "task.toml"
    text = path.read_text(encoding="utf-8")
    original = TaskConfig.model_validate_toml(text)
    if original.steps:
        raise ValueError("Only single-step Unreal tasks are supported")
    existing_definition = task / "tests/Dockerfile"
    generated = existing_definition.is_file() and existing_definition.read_text(encoding="utf-8").startswith(GENERATED_HEADER)
    if original.verifier.user is not None and not (original.verifier.user == "root" and generated):
        raise ValueError("Custom verifier users require task-specific preparation")
    if (task / "tests" / ORIGINAL_TEST).exists():
        raise ValueError(f"Reserved verifier entrypoint path already exists: tests/{ORIGINAL_TEST}")
    # Existing repository packages have a one-line top-level artifact array.
    # Refuse other layouts instead of accidentally editing nested declarations.
    match = re.search(r"(?m)^artifacts\s*=\s*\[.*\]\s*$", text.split("[task]", 1)[0])
    if not match:
        raise ValueError("Expected a one-line top-level artifacts array before [task]")
    text = text[:match.start()] + artifact_toml(artifacts) + "\n" + text[match.end():]
    start = text.index("[verifier]") + len("[verifier]")
    end = text.find("\n[", start)
    end = len(text) if end < 0 else end
    section = text[start:end]
    if re.search(r"(?m)^environment_mode\s*=", section):
        section = re.sub(r'(?m)^environment_mode\s*=.*$', 'environment_mode = "separate"', section)
    else:
        section = '\nenvironment_mode = "separate"' + section
    if re.search(r"(?m)^user\s*=", section):
        section = re.sub(r'(?m)^user\s*=.*$', 'user = "root"', section)
    else:
        section = '\nuser = "root"' + section
    text = text[:start] + section + text[end:]
    configured = TaskConfig.model_validate_toml(text)
    if configured.task != original.task:
        raise ValueError("Task identity changed unexpectedly")
    if configured.verifier.environment is not None or configured.environment.docker_image:
        raise ValueError("Prebuilt/custom verifier environments require a task-specific preparation")
    dockerfile = (task / "environment/Dockerfile").read_text(encoding="utf-8")
    workspace_line = "COPY --chown=ue4:ue4 workspace/ /project/"
    if dockerfile.count(workspace_line) != 1:
        raise ValueError("Expected an Unreal Dockerfile with a workspace copy to /project")
    tests = task / "tests"
    agent_compose = task / "environment/docker-compose.yaml"
    if agent_compose.exists() and agent_compose.read_text(encoding='utf-8') not in {GPU_AGENT_COMPOSE, LEGACY_GPU_AGENT_COMPOSE}:
        raise ValueError("Custom agent Compose services require task-specific verifier preparation")
    if (tests / "docker-compose.yaml").exists() and (tests / "docker-compose.yaml").read_text(encoding="utf-8") not in {COMPOSE, LEGACY_COMPOSE, GPU_COMPOSE, LEGACY_GPU_COMPOSE}:
        raise ValueError("Refusing to replace a custom verifier Compose definition")
    if (tests / "Dockerfile").exists():
        existing = (tests / "Dockerfile").read_text(encoding="utf-8")
        if not existing.startswith(GENERATED_HEADER) and existing not in {
            dockerfile, dockerfile.replace(workspace_line + "\n", "")
        }:
            raise ValueError("Refusing to replace a custom verifier Dockerfile")
    if (tests / "Dockerfile.dockerignore").exists() and (tests / "Dockerfile.dockerignore").read_text(encoding="utf-8") != BUILD_IGNORE:
        raise ValueError("Refusing to replace custom verifier build-context exclusions")
    tests.mkdir(exist_ok=True)
    if agent_compose.exists():
        agent_compose.write_text(GPU_AGENT_COMPOSE, encoding='utf-8', newline='\n')
    # Harbor skips test uploads for separate verification: the image MUST own
    # /tests. A task-root context reaches both trusted environment/ and tests/;
    # the Dockerfile-specific ignore file excludes solution/ and other roots.
    (tests / "Dockerfile").write_text(verifier_dockerfile(task, partial_project=partial_project), encoding="utf-8", newline="\n")
    (tests / "docker-compose.yaml").write_text(verifier_compose(task), encoding="utf-8", newline="\n")
    (tests / "Dockerfile.dockerignore").write_text(BUILD_IGNORE, encoding="utf-8", newline="\n")
    path.write_text(text, encoding="utf-8", newline="\n")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("task", type=Path, nargs="+")
    args = parser.parse_args(argv)
    for task in args.task:
        configure_task(task)
        print(f"Configured native replay: {task}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
